services:
    database:
        image: mariadb
        container_name: PlatformaBaza
        environment:
            MARIADB_ROOT_PASSWORD: 1234
            MARIADB_DATABASE: PlatformaBaza
        ports:
            - 5010:3306
        volumes:
            - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data: