services:
    database:
        image: mariadb
        container_name: database
        environment:
          MARIADB_ROOT_PASSWORD: 1234
          MARIADB_DATABASE: PlatformaBaza
        ports:
          - 5010:3306
        networks:
          - internal-network
        volumes:
          - mariadb_data:/var/lib/mysql
    backend:
        build: .
        container_name: backend
        environment:
          RUNNING_IN_CONTAINER: true
          DOCKER_DB_SERVER: database
        ports:
          - 7124:8080
        networks:
          - internal-network
        links:
          - database
        depends_on:
          -  database
volumes:
    mariadb_data:
networks:
  internal-network: {}